version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: "db"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5431:5432
    restart: unless-stopped

  pgAdmin:
    container_name: "pg-admin"
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - 8081:8081

  nats:
    container_name: "nats-streaming"
    image: nats-streaming
    restart: unless-stopped
    ports:
      - 4222:4222
